name: ci

on:
  pull_request:
    branches: [master]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

# TODO(kevintownsend): Complete style checks.
